apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deploymentName }}
    release: {{ .Release.Name }}
  name: {{ .Values.deploymentName }}-svc
spec:
  ports:
  - name: {{ .Values.expose.serviceName }}
    port: {{ .Values.expose.port | default "80" }}
    protocol: TCP
    targetPort: {{ .Values.expose.targetPort }}
  selector:
    app: {{ .Values.deploymentName }}
  type: {{ .Values.expose.serviceType }}